# This workflow will do a clean install of swift dependencies, build the source code and run tests across different versions of swift
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-swift-with-github-actions

name: Swift CI

on:
  push:
    branches: [ main, 1.x ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-lint:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.7.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Lint
        run: swiftlint lint --config Plugins/SwiftLintPlugin/swiftlint.yml

  unit:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.7.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Lint
        run: swiftlint lint --config Plugins/SwiftLintPlugin/swiftlint.yml
      - name: Run tests
        run: swift test --filter XRPLSwiftUTests