# This workflow will do a clean install of swift dependencies, build the source code and run tests across different versions of swift
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-swift-with-github-actions

name: Swift CI

on:
  push:
    branches: [ main, 1.x ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-lint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Swift "5.6.0"
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6.0"
    - run: swift build
    - run: swiftlint lint --config Plugins/SwiftLintPlugin/swiftlint.yml 

  unit:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Swift "5.6.0"
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6.0"
    - run: swift build
    - run: swiftlint lint --config Plugins/SwiftLintPlugin/swiftlint.yml 
    - run: swift test --filter XRPLSwiftUTests

  # integration:
  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - run: brew install --cask docker
  #   - run: docker run -d -p 6006:6006 -it natenichols/rippled-standalone:latest
  #   - name: Use Swift "5.6.0"
  #     uses: swift-actions/setup-swift@v1
  #     with:
  #       swift-version: "5.6.0"
  #   - run: swift build
  #   - run: swiftlint lint
  #   - run: swift test --filter XRPLSwiftITests
  #     env:
  #       HOST: localhost
  #       PORT: ${{ job.services.rippled.ports['6006'] }}